"""ACDC multiclass cardiac MRI segmentation dataset.

Two-dimensional short-axis slices extracted from the labeled end-diastole
and end-systole frames of the Automated Cardiac Diagnosis Challenge. See
``scripts/data/prepare_acdc.py`` for the preprocessing pipeline that produces
the image/label layout expected here.
"""

import json
from pathlib import Path
from typing import Any

import numpy as np
import torch
from PIL import Image

from src.configs.dataset import DatasetConfig

from .base import BaseSegmentationDataset
from .registry import register_dataset
from .transforms import SegmentationTransform, build_segmentation_transform


# Paper augmentation recipe (MoE-SAM): flipping, rotation, scaling and
# intensity shifting. Applied to the training split only.
TRAIN_AUGMENTATION_KWARGS = {
    "horizontal_flip_probability": 0.5,
    "vertical_flip_probability": 0.5,
    "rotation_range": 15.0,
    "scaling_range": (0.8, 1.2),
    "intensity_shift_range": 0.1,
}


@register_dataset("acdc")
class ACDCDataset(BaseSegmentationDataset):
    """Read ACDC image-mask pairs generated by prepare_acdc.py.

    Images are normalized 8-bit PNGs and labels are compressed ``.npz`` files
    holding a single ``uint8`` array of class indices:
    ``{0: background, 1: RV, 2: MYO, 3: LV}``.
    """

    MANIFEST_SPLITS = {
        "train": "training",
        "val": "validation",
        "test": "test",
    }

    def __init__(self, config: DatasetConfig, split: str, transform = None) -> None:
        super().__init__(config = config, split = split, transform = transform)

        if config.task != "multiclass":
            raise ValueError(
                "ACDCDataset requires task='multiclass' with num_classes=4."
            )

        self.root = Path(config.root).expanduser().resolve()
        manifest_path = Path(config.manifest).expanduser().resolve()

        if not manifest_path.is_file():
            raise FileNotFoundError(
                f"Dataset manifest not found: {manifest_path}"
            )

        with manifest_path.open("r", encoding="utf-8") as file:
            manifest: dict[str, Any] = json.load(file)

        manifest_split = self.MANIFEST_SPLITS.get(split, split)
        records = manifest.get(manifest_split)

        if not isinstance(records, list):
            raise ValueError(
                f"Split '{manifest_split}' is missing or invalid in "
                f"{manifest_path}."
            )
        if not records:
            raise ValueError(f"Split '{split}' contains no samples.")

        self.records = records
        self.transform = transform or self._default_transform(split)

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, index: int) -> dict[str, Any]:
        record = self.records[index]
        image_path = self.root / record["image"]
        mask_path = self.root / record["label"]

        if not image_path.is_file():
            raise FileNotFoundError(f"Image not found: {image_path}")
        if not mask_path.is_file():
            raise FileNotFoundError(f"Mask not found: {mask_path}")

        with Image.open(image_path) as image_file:
            image = image_file.convert("RGB")
            width, height = image.size

        mask = self._load_mask(mask_path, height = height, width = width)
        image, mask = self.transform(image, mask)
        mask = mask.long()

        return {
            "image": image,
            "mask": mask,
            "sample_id": Path(record["image"]).stem,
            "image_path": str(image_path),
            "mask_path": str(mask_path),
        }

    def _default_transform(self, split: str) -> SegmentationTransform:
        """Deterministic evaluation transform or paper training augmentation."""

        return SegmentationTransform(
            image_size=self.config.image_size,
            image_mean=self.config.image_mean,
            image_std=self.config.image_std,
            training=split == "train",
            **(TRAIN_AUGMENTATION_KWARGS if split == "train" else {}),
        )

    @staticmethod
    def _load_mask(mask_path: Path, *, height: int, width: int) -> torch.Tensor:
        with np.load(mask_path) as archive:
            if "mask" not in archive:
                raise ValueError(f"Label file {mask_path} must contain a 'mask' array.")
            dense_mask = np.asarray(archive["mask"])

        if dense_mask.ndim != 2:
            raise ValueError(
                f"Label file {mask_path} must contain a 2D mask, got "
                f"{dense_mask.ndim} dimensions."
            )
        if dense_mask.shape != (height, width):
            raise ValueError(
                f"Mask size mismatch for {mask_path}: expected "
                f"{(height, width)} for image size, got {dense_mask.shape}."
            )

        mask = np.asarray(dense_mask, dtype=np.int64).reshape(1, height, width)
        return torch.from_numpy(mask)
