"""AMOS22 CT multiclass abdominal organ segmentation dataset."""

from .ct_slice import CTSliceDataset
from .registry import register_dataset


@register_dataset("amos22_ct")
class AMOS22Dataset(CTSliceDataset):
    """Read 2D CT slices generated by scripts/data/prepare_amos22.py."""
