"""ISIC 2018 binary skin-lesion segmentation dataset."""

import json
from pathlib import Path
from typing import Any

import numpy as np
import torch
from PIL import Image
from scipy import sparse

from src.configs.dataset import DatasetConfig

from .base import BaseSegmentationDataset
from .registry import register_dataset
from .transforms import build_segmentation_transform


@register_dataset("isic2018")
class ISIC2018Dataset(BaseSegmentationDataset):
    """Read image-mask pairs generated by prepare_isic2018.py."""

    MANIFEST_SPLITS = {
        "train": "training",
        "val": "validation",
        "test": "test",
    }

    def __init__(self, config: DatasetConfig, split: str, transform = None,) -> None:
        super().__init__(config = config, split = split, transform = transform)

        if config.task != "binary":
            raise ValueError(
                "ISIC2018Dataset currently supports binary segmentation only."
            )

        self.root = Path(config.root).expanduser().resolve()
        manifest_path = Path(config.manifest).expanduser().resolve()

        if not manifest_path.is_file():
            raise FileNotFoundError(
                f"Dataset manifest not found: {manifest_path}"
            )

        with manifest_path.open("r", encoding="utf-8") as file:
            manifest: dict[str, Any] = json.load(file)

        manifest_split = self.MANIFEST_SPLITS.get(split, split)
        records = manifest.get(manifest_split)

        if not isinstance(records, list):
            raise ValueError(
                f"Split '{manifest_split}' is missing or invalid in "
                f"{manifest_path}."
            )
        if not records:
            raise ValueError(f"Split '{split}' contains no samples.")

        self.records = records
        self.transform = transform or build_segmentation_transform(
            config,
            split,
        )

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, index: int) -> dict[str, Any]:
        record = self.records[index]
        image_path = self.root / record["image"]
        mask_path = self.root / record["label"]

        if not image_path.is_file():
            raise FileNotFoundError(f"Image not found: {image_path}")
        if not mask_path.is_file():
            raise FileNotFoundError(f"Mask not found: {mask_path}")

        with Image.open(image_path) as image_file:
            image = image_file.convert("RGB")
            width, height = image.size

        mask = self._load_mask(mask_path, height = height, width = width)
        image, mask = self.transform(image, mask)
        mask = (mask >= self.config.mask_threshold).float()

        return {
            "image": image,
            "mask": mask,
            "sample_id": Path(record["image"]).stem,
            "image_path": str(image_path),
            "mask_path": str(mask_path),
        }

    @staticmethod
    def _load_mask(mask_path: Path, *, height: int, width: int,) -> torch.Tensor:
        sparse_mask = sparse.load_npz(mask_path) #sparse chỉ lưu toạ độ pixel = 1, save memory và load lên RAM nhanh hơn
        dense_mask = sparse_mask.toarray()

        expected_elements = height * width
        if dense_mask.size != expected_elements:
            raise ValueError(
                f"Mask size mismatch for {mask_path}: expected "
                f"{expected_elements} elements for image {(height, width)}, "
                f"got {dense_mask.size}."
            )

        mask = np.asarray(
            dense_mask,
            dtype=np.float32,
        ).reshape(1, height, width)
        return torch.from_numpy(mask)
