"""Synapse/BTCV multiclass abdominal organ segmentation dataset."""

from .ct_slice import CTSliceDataset
from .registry import register_dataset


@register_dataset("synapse_btcv")
class SynapseDataset(CTSliceDataset):
    """Read 2D CT slices generated by scripts/data/prepare_synapse.py."""
